#
#  ArduTracker Server 
#
#  Eclipse Mosquitto (with MQTT) + Web panel
#  + Database + Collector

version: '2'

networks:
  ardu-tracker-net:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: at_mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - ardu-tracker-net
    environment:
      - TZ=Europe/Rome
  collector:    
    container_name: at_collector
    build: ./collector
    networks:
      - ardu-tracker-net
    depends_on: 
      - mosquitto
  webapp:
    build: ./webapp
    container_name: at_webapp
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "8080:80"
      - "4430:443"
    volumes: 
      - ./webapp:/var/www/html/
    networks:
      - ardu-tracker-net

# TODO: database MYSQL (currently externally hosted)
