#
#  ArduTracker Server 
#
#  Eclipse Mosquitto (with MQTT) + Database + Web panel
#

version: '2'

networks:
  ardu-tracker-net:
    driver: bridge

services:
   mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - ardu-tracker-net
    environment:
      - TZ=Europe/Rome

# TODO: data collector
# TODO: database MYSQL
# TODO: Web panel
