#
#  ArduTracker Server 
#
#  Eclipse Mosquitto (with MQTT) + Web panel
#  + Database + Collector

version: '2'

networks:
  ardu-tracker-net:
    driver: bridge

volumes:
  db_data:

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: at_mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - ardu-tracker-net
    environment:
      - TZ=Europe/Rome
  collector:    
    container_name: at_collector
    build: ./collector
    networks:
      - ardu-tracker-net
    depends_on: 
      - mosquitto
  webapp:
    build: ./webapp
    container_name: at_webapp
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "8080:80"
      - "4430:443"
    volumes: 
      - ./webapp:/var/www/html/
    networks:
      - ardu-tracker-net
    depends_on: 
      - database
  database:
    image: mysql:5.7
    container_name: at_database
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: superSecurePassword
      MYSQL_DATABASE: ardutrackerdb
      MYSQL_USER: admin_ardutrack
      MYSQL_PASSWORD: 1q9p7lETVi
    networks:
      - ardu-tracker-net
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: at_phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: superSecurePassword
    networks:
      - ardu-tracker-net
    depends_on:
      - database